### PR TITLE
Fix string splitting

### LINKED ISSUE #488: RoqTemplateExtension.asStrings() doesn't seem to support space-delimited strings
In a site I'm working on, we have tags defined in FM like this: 

```
tags: oidc Keycloak JWT encryption authentication
```

When the tagging plugin parses that via `RoqTemplateExtension.asStrings()` , we get a single tag back: `oidc-Keycloak-JWT-encryption-authentication`, which is obviously not correct. :) If I call `String.split(" ")` on the string, we get the expected array of 5 tags. I've looked at the regex used in the method, and it _seems_ like it should work, but it isn't for some reason, and regex fu is apparently not quite good enough to figure out why. :)

### PR DESCRIPTION
**Pull request by jasondlee**
Modify string split regex to cover more cases
Trim each tag
Filter out empty tags

Fixes #488

### CODE REVIEW

File: roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/RoqTemplateExtension.java [hunk 1]
```diff
@@ -46,14 +47,25 @@ public static String slugify(String text) {
...
+                    .filter(s -> !s.isEmpty())
+                    .toList();
         }
         if (o instanceof JsonArray i) {
             return i.getList();
         }
         return List.of();
     }
 
+    public static void main(String[] args) {
```
Comment (ia3andy) [inline roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/RoqTemplateExtension.java]: Could we have a test instead :)

**Review by ia3andy — CHANGES_REQUESTED** [review]

File: roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/RoqTemplateExtension.java (hunk 1 above)
Comment (jasondlee) [reply roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/RoqTemplateExtension.java]: haha. I thought I deleted that. But yes.

Comment (jasondlee) [reply roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/RoqTemplateExtension.java]: Took me a minute to figure out the import sort plugin, but I think this oughtta do it, assuming the test is in the right place. :)

**Review by ia3andy — APPROVED** [review]
LGTM
