### PR TITLE
FM attributes support for Asciidoc and fixes

### LINKED ISSUE #572: Duplicate Asciidoc title in 1.7.0.CR2
With both asciidoc plugins the title gets repeated in the content block.

Using asciidoc variant of  First Roq:

```
= The first Roq! (adoc)
:description: This is my first article ever made with Quarkus Roq
:image: blog.avif
:tags: blogging
:author: roqqy
:page-cool: this is cool :)
:page-fun: and fun!
:qute: true

You can access page data like this:
[source,asciidoc]
----
* \{page.data.cool}
* \{page.data.fun}
----
**will render ⤵**

* {page.data.cool}
* {page.data.fun}


There are a few helpers on the `page` variable (https://iamroq.com/docs/basics/#_variables[more on variables]):

[source,asciidoc]
----
> \{page.date.format('YYYY')}: \{page.description}
----
**will render ⤵**

> {page.date.format('YYYY')}: {page.description}

---

It's time to write awesome articles!

__Thank you!__

**PS** To make the tag work (link:{site.url.resolve('posts/tag/blogging')}[#blogging]) you need to https://iamroq.com/docs/plugins/#plugin-tagging[enable tagging].
```

I get

Image

### PR DESCRIPTION
**Pull request by ia3andy**
Fixes #572 

With this the post theme layout includes the `notitle` by default

### CODE REVIEW

File: roq-plugin/asciidoc-common/deployment/src/main/java/io/quarkiverse/roq/plugin/asciidoc/common/deployment/AsciidocHeaderParser.java [hunk 1]
```diff
@@ -58,12 +60,16 @@ public static JsonObject toPageData(Header header) {
...
             if (key.startsWith("page-")) {
-                pageData.put(key.substring(5), attributes.get(key));
+                final String value = attributes.get(key);
+                pageData.put(key.substring(5), value.isEmpty() ? true : value);
             }
         }
         if (!header.title().isBlank()) {
             pageData.put(Page.FM_TITLE, header.title());
         }
+        if (header.attributes().containsKey(Page.FM_DESCRIPTION) && !header.attributes().get(Page.FM_DESCRIPTION).isBlank()) {
```
Comment (jtama) [inline roq-plugin/asciidoc-common/deployment/src/main/java/io/quarkiverse/roq/plugin/asciidoc/common/deployment/AsciidocHeaderParser.java:70]: How do we make sure asciidoc attribute eventual description is not overriden by FM description.

If we don't we should then document the precedence.

File: roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/model/PageInfo.java [hunk 2]
```diff
@@ -28,6 +28,11 @@ public record PageInfo(
          */
         String dateString,
 
+        /**
+         * The markup (markdown, asciidoc) or null if none
+         */
+        String markup,
```
Comment (jtama) [inline roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/model/PageInfo.java:34]: What is this used for ?

**Review by jtama — COMMENTED** [review]
Just a few comments

File: roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/model/PageInfo.java (hunk 2 above)
Comment (ia3andy) [reply roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/model/PageInfo.java:34]: It is not used but would allow to do `if` in a layout for example based on the page markup

Comment (ia3andy) [reply roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/model/PageInfo.java:34]: (It was added to deal with the notitle, but then I thought it was cleaner/nicer to have attributes in the layout)

File: roq-plugin/asciidoc-common/deployment/src/main/java/io/quarkiverse/roq/plugin/asciidoc/common/deployment/AsciidocHeaderParser.java (hunk 1 above)
Comment (ia3andy) [reply roq-plugin/asciidoc-common/deployment/src/main/java/io/quarkiverse/roq/plugin/asciidoc/common/deployment/AsciidocHeaderParser.java:70]: The FM parser has priority over the Asciidoc parser
Also, here, if asciidoc headers contains `description`, we add it to the data (but it won't override the FM)
